plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\VED\\OneDrive\\Desktop\\orbitx-future-labs-main\\orbitx-future-labs-main\\.netlify\\static"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\VED\\OneDrive\\Desktop\\orbitx-future-labs-main\\orbitx-future-labs-main"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]